export type TransactionType = 'income' | 'expense' | 'transfer';
export type CategoryType = 'income' | 'expense';
export type BudgetRhythm = 'weekly' | 'monthly' | 'yearly';
export type Theme = 'light' | 'dark';
export type DecimalSeparator = '.' | ',';
export type ConnectionStatus = 'pending' | 'active' | 'expired' | 'error';
export type BankEnvironment = 'sandbox' | 'production';
export type ConnectionType = 'manual' | 'sandbox' | 'linked';

/**
 * How a transaction's category was assigned. Populated by the
 * categorization engine after bank import OR by user action on manual
 * transactions / the review queue.
 */
export type CategorizationSource =
  | 'rule_auto'        // Stage 1/2: matched a learned or user-created rule
  | 'mcc_auto'         // Stage 3: matched via an MCC lookup
  | 'user_confirmed'   // User accepted the suggested category as-is
  | 'user_manual'      // User picked the category directly (manual txn)
  | 'user_corrected';  // User replaced a suggestion with a different category

/**
 * Status of a split expense (parent expense where the user has chosen
 * to track repayments from others). Null on non-split rows.
 */
export type SplitStatus = 'open' | 'settled';

/**
 * Discriminator on rows linked via related_transaction_id. Tells the
 * service layer whether a child row is a fee (generated by the existing
 * fee mechanism) or a repayment (from a split expense). Null on rows
 * that are not children of another transaction.
 */
export type RelationKind = 'fee' | 'repayment';

/**
 * Bank-settlement status of a transaction.
 *   - 'booked'  - settled by the bank (or any manual / legacy row). The
 *     default for every existing row and every manually-created one.
 *   - 'pending' - imported from the bank's pending set but not yet
 *     settled. Balance-neutral and excluded from all aggregations until
 *     it books (flips to 'booked' in place) or is auto-removed if it
 *     never settles. See bank-sync-service.ts / pending-reconcile.ts.
 */
export type TransactionStatus = 'pending' | 'booked';

/**
 * Cadence of a recurring expense series. Reuses the budget rhythm
 * vocabulary; `interval_days` on the series carries the learned/expected
 * gap and self-corrects once a second charge confirms the real cadence.
 */
export type RecurrenceCadence = 'weekly' | 'monthly' | 'yearly';

/**
 * Lifecycle of a recurring series.
 *   - 'active' - matched on import and shown in the groupings.
 *   - 'paused' - kept but dropped from the matcher and active groupings.
 *   - 'ended'  - the user stopped this commitment; dropped from the
 *     matcher and active groupings. Transactions keep their links.
 */
export type RecurringStatus = 'active' | 'paused' | 'ended';

/**
 * How a recurring series came to exist.
 *   - 'user'           - created via the Recurring toggle (v1).
 *   - 'auto_suggested' - reserved for a future cadence-based discovery
 *     pass; not produced in v1.
 */
export type RecurringSeriesSource = 'user' | 'auto_suggested';
