use tauri::Manager;
use tauri_plugin_deep_link::DeepLinkExt;
use tauri_plugin_sql::{Migration, MigrationKind};

mod secrets;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Migration v2 concatenates: (a) drop-v1-tables script, (b) schema-v2
    // CREATE statements. Existing v1 rows are wiped — the v1→v2 split is
    // not data-preserving.
    const MIGRATION_V2_SQL: &str = concat!(
        include_str!("../../src/db/migration-v2.sql"),
        "\n",
        include_str!("../../src/db/schema-v2.sql"),
    );

    let migrations = vec![
        Migration {
            version: 1,
            description: "Initial profile-aware schema",
            sql: include_str!("../../src/db/schema.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "User + koinkat account split",
            sql: MIGRATION_V2_SQL,
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "Transfer-pair detection columns",
            sql: include_str!("../../src/db/migration-v3.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 4,
            description: "Replace tags with categories + rule engine",
            sql: include_str!("../../src/db/migration-v4.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 5,
            description: "Dated budget events + sum-to-budget linkage",
            sql: include_str!("../../src/db/migration-v5.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 6,
            description: "Split expense reconciliation columns",
            sql: include_str!("../../src/db/migration-v6.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 7,
            description: "Bank-link user-chosen sync start date",
            sql: include_str!("../../src/db/migration-v7.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 8,
            description: "External (untracked) split reimbursements",
            sql: include_str!("../../src/db/migration-v8.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 9,
            description: "Manual-only flag for budget events",
            sql: include_str!("../../src/db/migration-v9.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 10,
            description: "Pending-transaction lifecycle columns",
            sql: include_str!("../../src/db/migration-v10.sql"),
            kind: MigrationKind::Up,
        },
        Migration {
            version: 11,
            description: "Recurring expense series",
            sql: include_str!("../../src/db/migration-v11.sql"),
            kind: MigrationKind::Up,
        },
    ];

    let mut builder = tauri::Builder::default();

    // On desktop, single-instance must be registered BEFORE deep-link so
    // that on Windows/Linux (where deep links arrive as a new process's
    // CLI args) the existing instance is focused and receives the URL.
    #[cfg(desktop)]
    {
        builder = builder.plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            let _ = app
                .get_webview_window("main")
                .map(|w| w.set_focus());
        }));
    }

    builder
        .plugin(tauri_plugin_deep_link::init())
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations("sqlite:koinkat.db", migrations)
                .build(),
        )
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        // The one set of app-defined commands: OS-keychain storage for the
        // Enable Banking private key (see secrets.rs for the rationale).
        .invoke_handler(tauri::generate_handler![
            secrets::secret_set,
            secrets::secret_get,
            secrets::secret_delete
        ])
        .setup(|app| {
            // Register the koinkat:// URL scheme on Windows and Linux.
            // macOS handles scheme registration via Info.plist (generated by Tauri).
            #[cfg(any(windows, target_os = "linux"))]
            app.deep_link().register_all()?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
